회원 인증 API 업데이트 및 변경
zoopi-palette/zoopi-spring-backend pull request #25
Opened 2022-07-17 09:59 UTC by seonpilKim

## 📌 Linked Issues
- Resolve: #24 
- See Also: #19  

## 🔎 Change Details
### 회원 인증 API 관련 사항
#### 1. 아이디 찾기 API 추가
![image](https://user-images.githubusercontent.com/68049320/179392559-cafb24c4-d810-4e75-bf14-c1827b3ce24e.png)

#### 2. 비밀번호 찾기 API 추가
![image](https://user-images.githubusercontent.com/68049320/179392515-46b07f45-f135-49fa-8813-9f4633a565a2.png)

#### 3. 일반 회원 가입 API 로직 순서 조정
![image](https://user-images.githubusercontent.com/68049320/179392488-7ab0a7cf-5074-444a-a661-e829db9baffa.png)

#### 4. 휴대폰 본인 인증 문자 전송 API 로직 업데이트
- 회원 가입 / 아이디 찾기 / 비밀번호 찾기를 구분하여 db에 저장
    - ![image](https://user-images.githubusercontent.com/68049320/179392624-e89764d9-3a6a-4374-9528-3a7c39b6afa8.png)
    - 각각 5분 이내로 5회 이상 호출 시 따로 밴 처리를 하기 위함
        > ex) 아이디 찾기에서 5분 이내로 5회 이상 문자 전송 API를 호출하여 1시간동안 밴 처리가 된 상황 <br>
        > 해당 휴대폰으로 비밀번호 찾기 및 회원 가입 과정에서 문자 전송 API 호출 가능
    - 인증 성공 / 실패 여부와 상관 없이 5분 이내로 5회 이상 문자 전송 API를 호출한 경우, 1시간 동안 밴 처리

#### 5. MemberAuthority 엔티티 제거
- 회원 권한을 Member 엔티티의 `String authorities`에 `ROLE_USER,ROLE_ADMIN` 이런식으로 저장하는 방식으로 변경하였습니다.
- 기존에는 MemberAuthority 엔티티에 저장하였는데, 이는 Many-To-Many 관계가 형성되어 테이블을 하나 더 추가해야하는 번거로움이 존재하여 위와 같이 변경하였습니다.

### ResponseMapper 클래스 추가
- Controller단에서 여러가지 경우의 응답이 발생하게 되어 코드가 복잡해지는 문제가 발생하였습니다.
- 이를 따로 ResponseMapper 클래스로 분리하여, 해당 클래스에서 ResultResponse를 만들어서 반환하도록 역할을 분리하였습니다.
- 아직 개선할 게 많아 보이긴 하지만, 이런식으로 여러 경우의 응답이 발생할 수 있는 경우에는 따로 클래스를 분리해서 ResultResponse를 생성하면 어떨지 다른 분들의 의견을 여쭙고 싶습니다..!

### 기타
- 누락된 Validation 어노테이션 추가
- 누락된 Swagger 어노테이션 추가
- 멤버 변수 네이밍 변경에 따른 JPA 메소드명 변경
    >  xxx`Date` -> xxx`At`
- JwtUtils, Oauth2 관련 클래스 리팩토링

## 💬 Comment
혹시 위의 사진[(diagram)](https://drive.google.com/file/d/1b8tKj3aLVKCe-9fbVz100jI19vvgf1q_/view?usp=sharing)과 같이 API 호출 과정을 도식화해서 관리하면 어떨까요?
한 눈에 로직 흐름을 파악하기도 쉽고, 구체적인 진행 방식을 다른 파트 분야에게 전달하면 좀 더 쉽게 소통할 수 있을 것 같습니다!

## 📑 References
- 

## ✅ Check Lists
- [ ] 추가한 기능에 대한 테스트는 모두 완료하셨나요?
- [ ] 코드 정렬(Ctrl + Alt + L), 불필요한 코드나 오타는 없는지 확인하셨나요?
- [ ] merge할 base branch가 올바른지 확인하셨나요?

2022-07-17 11:08 UTC, dongkyunkimdev commented
아 선필님 이건 코드리뷰 외적인 거긴 한데, Resolve: #24 등의 키워드로 merge 되는 순간 issue auto close를 하고 싶으신 거라면 default branch를 병합되는 브랜치로 설정해야 적용되는 걸로 알고있습니다!
저희의 경우 현재 default branch가 master로 되어있는데, 개발 브랜치인 develop으로 바꿔야 하는 것 같습니다!
그래서 현재 resolve 키워드를 사용하고 있음에도 우측 Development 탭에 issue link가 걸려있지 않습니닷
![image](https://user-images.githubusercontent.com/49021557/179395258-e52939d9-ab60-4e10-8773-2854bf15fac1.png)

issue auto close를 하려고 하신 게 아니라면,, 죄송합니다,,

2022-07-17 11:18 UTC, seonpilKim commented
아하 어쩐지 키워드 추가해도 계속 연결이 안되더라구요.. 릴리즈 전까지는 develop 브런치를 default로 바꿔놓겠습니다!🙏

2022-07-17 12:47 UTC, seonpilKim commented
추가로, 클라이언트(android)에서 소셜 로그인을 통한 간편 로그인은 기존의 Security 방식과 다르게 구현해야 할 것 같습니다.

front는 redirect url을 통해 로그인 정보를 백엔드 서버에서 받을 수 있는데, 안드로이드는 url이란 개념이 없으니까 기존 방식으로는 구현이 힘들 것 같더라구요..
그래서 클라이언트단에서 소셜 로그인을 구현해서, 로그인이 완료되고 얻는 AccessToken을 저희 서버로 전달해 주면, 저희가 이 토큰으로 naver의 회원 프로필 조회 API를 호출해서 id, email, phone 정보를 얻어오는 방식으로 진행하면 어떨까 싶습니다.
> [네이버 회원 프로필 조회 api 명세](https://developers.naver.com/docs/login/profile/profile.md#%EB%84%A4%EC%9D%B4%EB%B2%84-%ED%9A%8C%EC%9B%90-%ED%94%84%EB%A1%9C%ED%95%84-%EC%A1%B0%ED%9A%8C-api-%EB%AA%85%EC%84%B8)
추후에 벤더가 추가되더라도 잘 추상화 해 두면 문제 없을 것 같습니다.

2022-07-18 11:52 UTC, slolee commented
혹시 현재 핸드폰 인증 목적으로 사용되고 있는 테이블 Authentication 을 PhoneAuthentication 와 같이 변경 하는 것은 어떨까요..?
인증이라는 개념이 여기저기서 사용되다보니 약간 혼동이 있을 수 있을듯 합니다 :)

2022-07-18 13:17 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/authentication/service/AuthenticationService.java
> +		authenticationRepository.save(new Authentication(uuid, authenticationCode, phone, type));
`Authentication.of(authenticationCode, phone, type)` 와 같이 새로운 Entity 를 생성하고 UUID 생성하는 로직을 도메인 로직으로 포함시키면 서비스를 봤을 때 좀 더 비즈니스 로직 흐름이 한눈에 보일 것 같습니다!!

2022-07-18 13:17 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/authentication/service/AuthenticationService.java
`public AuthenticationResult checkAuthenticationCode(String authenticationCode, String phone, String authenticationKey)` 해당 메소드에서

isExpired, isMatch, isMine 을 구하는 부분을 도메인 로직으로 넣는건 어떨까요?
그럼 서비스쪽 비즈니스 로직 흐름상에서

```java
if(authentication.isExpired()) { ... }
else if(authentication.isMatch(authenticationCode) && authentication.isMine(phone)) { ... }
else { ... }
```
정도로 좀 더 간결하게 정리될 수 있을 것 같습니다 :)

2022-07-18 13:17 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/authentication/service/AuthenticationService.java
> +	public AuthenticationResult validateAuthenticationKey(String phone, String authenticationKey,
위 `checkAuthenticationCode()` 관련 코멘트와 동일한 내용입니다!!

2022-07-18 13:17 UTC, slolee commented on module-domain/src/main/java/com/zoopi/config/security/oauth2/CustomOAuth2UserService.java
> +	public OAuth2User loadUser(OAuth2UserRequest userRequest) {
흑흑.. 이쪽 코드 너무 어렵네요 ㅠㅠ
OAuth2Attributes 클래스로 조금 더 넣어서 비즈니스 로직을 추상화하면 어떨까요??

2022-07-18 13:17 UTC, slolee commented on module-api/src/main/java/com/zoopi/controller/member/mapper/FindPasswordResponseMapper.java
> +package com.zoopi.controller.member.mapper;
Mapper 로 분리해서 컨트롤러 코드 정리한것 좋아요 👍 👍 👍

2022-07-18 13:17 UTC, slolee commented on module-api/src/main/java/com/zoopi/controller/member/mapper/FindPasswordResponseMapper.java
> +package com.zoopi.controller.member.mapper;
Repsonse 클래스의 팩토리 메소드를 이용하는 것도 하나의 방법일 것 같아요!

2022-07-26 13:17 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/domain/authentication/service/AuthenticationService.java
> +		authenticationRepository.save(new Authentication(uuid, authenticationCode, phone, type));
넵 고려해서 리팩토링 해보겠습니다!

2022-07-26 13:22 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/domain/authentication/service/AuthenticationService.java
오 확실히 간결해지고 좋네요!! 도메인 로직으로 변경해보겠습니다!

2022-07-26 13:25 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/config/security/oauth2/CustomOAuth2UserService.java
> +	public OAuth2User loadUser(OAuth2UserRequest userRequest) {
넵 알겠습니다ㅎㅎ 많이 고민해서 수정해볼게요!

2022-07-26 13:31 UTC, seonpilKim commented on module-api/src/main/java/com/zoopi/controller/member/mapper/FindPasswordResponseMapper.java
> +package com.zoopi.controller.member.mapper;
Response 클래스의 팩토리 메소드도 좋은 방법인 것 같아요!
아직 고민 중인 부분이었는데, 이 방식도 참고해서 조금 더 고민해보겠습니다🙂

2022-07-30 07:02 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/authentication/repository/AuthenticationRepository.java
> +	List<Authentication> findAllByStatusAndCreatedAtAfter(AuthenticationStatus status, LocalDateTime date);
이걸 사용하는 테스트코드쪽도 함께 수정이 필요해 보입니다 :-)

2022-07-31 10:58 UTC, slolee commented
![image](https://user-images.githubusercontent.com/38906956/182022919-a7bc97ca-8096-42ea-9dc0-8e8ab21a6683.png)
@seonpilKim  수정된 비즈니스스 로직에 대한 테스트코드 반영이 안되어있는것 같습니다!
확인 부탁드려요 :)

2022-07-31 12:54 UTC, slolee requested changes

2022-07-31 12:54 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/dto/response/PhoneAuthenticationResponse.java
> +}
Response 클래스는 Endpoint 에서 클라이언트에게 내려줄 데이터의 형태를 정의하는데, Domain 모듈에 존재하는게 조금 어색한 것 같아요! API 모듈로 옮기는 것에 대해서는 어떻게 생각하시나요?

2022-07-31 12:54 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/entity/PhoneAuthentication.java
> +	public PhoneAuthenticationResult check(String code) {
메소드명을 `checkCode` 으로 수정하는건 어떨까요?
동사만 써있으니 어떤걸 체크하는지 주석을 보지 않았을 때 이해하기 어려운것 같아요 :)

2022-07-31 12:54 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/service/PhoneAuthenticationBanService.java
> +	}
Optional 을 필드로 사용하게 되면 결국 뒤에서 If 문으로 한번 더 검증해야하는 코드가 들어가게 되어서 사용하지 않을때랑 큰 차이가 없을 것 같습니다. 추가로 Optional 이 등장한 취지 자체도 필드로 사용하는 것이 아니라 체이닝 메소드를 활요해 이후 핸들링을 하도록 한 것으로 알고 있습니다 :)

Optional 에서는 자체적으로 검증하고 이후 비즈니스 로직까지 처리할 수 있는 다양한 체이닝 메소드들을 제공하는데, 아래 코드처럼 그걸 활용해보면 어떨까요?

```java
@Transactional
public boolean isBanned(String phone, PhoneAuthenticationType type) {
  return phoneAuthenticationBanRepository.findByPhoneAndType(phone, type)
    .map(phoneAuthenticationBan -> {
        if (LocalDateTime.now().isAfter(phoneAuthenticationBan.getCreatedAt().plusDays(BAN_DAY))) {
          phoneAuthenticationBanRepository.delete(phoneAuthenticationBan);
          return false;
        }
        return true;
    }).orElse(false);
}
```

2022-07-31 12:54 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/service/PhoneAuthenticationService.java
> +@Transactional(readOnly = true)
여기에 `@Trasanctional` 어노테이션을 붙여준 이유가 있을까요?

2022-07-31 12:54 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/service/PhoneAuthenticationService.java
> +		return PhoneAuthenticationResponse.of(phoneAuthentication);
데이터베이스에 저장하기 전에 생성해 둔 엔티티 객체를 반환하게되면, save 과정에서 채번된 id 같은 필드가 없는채로 반환될 것 같아요.

아래와 같이 save 메소드가 생성된 엔티티 객체를 반환하고 있으니, 그걸 반환하도록 구성하는건 어떨까요?
```java
final PhoneAuthentication phoneAuthentication = PhoneAuthentication.of(authenticationCode, phone, type);
return PhoneAuthenticationResponse.of(phoneAuthenticationRepository.save(phoneAuthentication));
```

2022-07-31 12:54 UTC, slolee commented on module-domain/src/main/java/com/zoopi/config/security/oauth2/CustomOAuth2UserService.java
>  		}
Optional 에 대한 중복 코멘트인데, 아래와 같이 수정하는건 어떨지 의견드립니다 ㅎㅎ

```java
private Member loadMember(OAuth2UserRequest userRequest, OAuth2Attributes oAuth2Attributes) {
  final SnsAccountPrimaryKey primaryKey = getSnsAccountPrimaryKey(userRequest);
  return snsAccountService.getWithMember(primaryKey)
		.map(SnsAccount::getMember)
		.orElse(signup(primaryKey, oAuth2Attributes.getEmail(), oAuth2Attributes.getPhone()));
}
```

2022-07-31 12:54 UTC, slolee commented on module-domain/src/main/java/com/zoopi/config/security/oauth2/CustomOAuth2UserService.java
>  		return member;
`snsAccountService.connect(member, primaryKey)` 를 호출하기 전에 생성한 member 객체를 그대로 반환하고 있는것 같습니다. connect 메소드의 로직이 바뀌거나 뭔가 Member 엔티티 객체을 수정하는 작업이 포함된다면 그 부분이 반영되지 않은 객체가 리턴될 것 같습니다.

예를들어 새로운 Member 엔티티 객체를 save 할 때 채번되는 Id 값이 반영되지 않은 엔티티 객체를 반환할 수 없을 것 같아요!

2022-07-31 12:54 UTC, slolee commented on module-domain/src/main/java/com/zoopi/config/security/oauth2/OAuth2Attributes.java
>  		}
Enum class 의 추상화된 메소드인 valueOf 메소드를 사용하면 어떨까요?
비즈니스 로직상에 반복문이 노출되지 않아 좀 더 흐름을 명확히 파악할 수 있을 것 같습니다!

```java
public static OAuth2Attributes of(OAuth2UserRequest userRequest, OAuth2User oAuth2User) {
    try {
	  final String registrationId = userRequest.getClientRegistration().getRegistrationId();
	  return of(SnsProvider.valueOf(registrationId), userRequest, oAuth2User.getAttributes());
    } catch (Exception e) {
	  throw new UnsupportedPlatformSignInException();
    }
}
```

2022-08-01 08:55 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/service/PhoneAuthenticationService.java
> +		return PhoneAuthenticationResponse.of(phoneAuthentication);
jpa가 동일성을 보장해줘서 save하는 시점에 위의 phoneAuthentication 인스턴스에 id값을 넣어주는 것으로 알고 있습니다..!-> save 메소드 호출 이후로 phoneAuthentication.getId()를 호출해 보면 정상적으로 id값을 가져오는 것을 다시 한 번 확인하였습니다👍

다만 Auditing 기능은 위와 같이 동작하지 않아서 결국 save 메소드의 반환값을 이용해야 phoneAuthentication.getCreateAt()을 정상적으로 가져올 수 있었습니다.
Auditing은 동작 방식이 다르다는 것을 테스트코드 작성하면서 처음 알게 되어서 테스트 코드 작성의 중요성을 다시 한 번 깨닫게 되었네요😂

2022-08-01 08:57 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/config/security/oauth2/OAuth2Attributes.java
>  		}
오 좋은 방법인 것 같습니다! 👍👍

2022-08-01 09:09 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/service/PhoneAuthenticationService.java
> +@Transactional(readOnly = true)
단순히 구현 편의성을 위한 의도로 생각해 주시면 될 것 같습니다!

`@Transcational(readOnly = true)`를 단순 조회 쿼리가 발생하는 메소드마다 추가해 주는 건 불편하다고 생각되어 클래스단위에 추가해 두고, 엔티티의 추가/삭제/변경이 발생하는 메소드에만 추가로 `@Transactional`을 명시해서 오버라이딩해서 사용하는 방식입니다!

2022-08-01 09:12 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/service/PhoneAuthenticationBanService.java
> +	}
저도 구현하면서 따로 체이닝 메소드를 사용하는 방법이 있지 않을까 고민했었는데, 이렇게 코드까지 친절히 알려주시다니ㅠㅠㅠ 감사합니다! 바로 적용하도록 할게요👍👍

2022-08-01 09:14 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/entity/PhoneAuthentication.java
> +	public PhoneAuthenticationResult check(String code) {
그러셨군요 ㅠ_ㅠ 메소드명+파라미터명으로 의도가 전달되지 않을까 생각했었는데..! 메소드명을 조금 더 친절하게 정해야겠네요🙂

2022-08-01 09:18 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/dto/response/PhoneAuthenticationResponse.java
> +}
이부분은 아직 고민이 있는 부분인데요..
api 모듈이 domain 모듈을 의존하는 형태이다 보니, Response 클래스를 api 모듈로 옮기면 domain 모듈에서는 해당 클래스를 사용할 수 없게 되어서 동일한 구조의 클래스(dto)를 하나 더 만들어야해서요..
혹시 찬준님은 어떤 방식이 더 마음에 드실까요..?

1. domain 모듈에서는 네이밍을 dto로 변경하고, api 모듈에 동일한 구조의 response 클래스를 생성하여 사용
2. 귀찮으니 현재 방식으로 사용🙃
3. 다른 방식(?)

2022-08-03 10:12 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/entity/PhoneAuthentication.java
> +	public PhoneAuthenticationResult check(String code) {
물론 이 파일을 들어왔을땐 충분히 이해할수 있다고 생각하는데,, 사용하는 곳 입장에서 판단하기 어려울 것 같아 드린 코멘트입니다!

2022-08-03 10:13 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/service/PhoneAuthenticationService.java
> +@Transactional(readOnly = true)
구현상 편의성을 얻는대신 어느 메소드가 트랜잭션처리가 필요한 곳인지 불분명해지는 부분은 있는것 같아요!
코멘트 감사드립니다 👍

2022-08-03 10:15 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/service/PhoneAuthenticationService.java
> +		return PhoneAuthenticationResponse.of(phoneAuthentication);
오 그것은 몰랐던부분이네요! 좋은 답변 감사드려요 👍 👍

2022-08-03 13:05 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/service/PhoneAuthenticationService.java
> +@Transactional(readOnly = true)
오늘 마침 회사 멘토분이랑 트랜잭션 관련된 이야기를 잠깐나눴었는데 찬준님이랑 똑같은 말씀을 하시더라구요..! 트랜잭션이 꼭 필요한 곳에만 명시하는게 좋을 것 같다는 생각을 갖게 되었습니다.

2022-08-05 12:15 UTC, slolee commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/dto/response/PhoneAuthenticationResponse.java
> +}
동일한걸 만들필요없이 해당 클래스를 api 쪽으로 이동하는건 어떨까요?

2022-08-05 12:45 UTC, slolee approved these changes
우선 이정도에서 머지하고 진행해요!
다음부터는 PR 을 조금 작게 올려주시면 감사하겠습니다 :)
너무 크니까 한번에 보기도 힘들고, 코멘트내용이 반영되어도 그 부분을 다시 찾아보는게 힘드네요~

2022-08-05 13:47 UTC, seonpilKim commented on module-domain/src/main/java/com/zoopi/domain/phoneauthentication/dto/response/PhoneAuthenticationResponse.java
> +}
단순 이동은 아래 메시지와 같이 참조가 불가능해지는 문제가 발생해서요 ㅠ_ㅠ
![image](https://user-images.githubusercontent.com/68049320/183083792-f3ac173d-cf7e-4629-b0a6-e758286491c6.png)

일단 여러가지 방식으로 고민하고 있는게 있는데, 이는 따로 이슈로 올리도록 하겠습니다.

2022-08-05 13:48 UTC, merged

2022-08-05 13:51 UTC, seonpilKim commented
의도치않게 변경파일이 너무 많이 쌓였네요.. 좀 더 신경써서 작은 단위로 PR을 올리도록 노력하겠습니다!